### ISSUE TITLE
csgo-practice mode crash (CSGO Update)

### ISSUE THREAD

**Issue by MikkelDK** [splewis/csgo-practice-mode#133]
If reporting a bug, fill in the following sections:

### Expected behavior
Problems with loading csgo-practicemode - Server crash.

### Actual behavior
Server crash.

### Steps to reproduce
- Plugin version: 295-dev version
- Sourcemod version: 1.10-6455
- Steps to reproduce (please be specific): Install sourcemod 1.10-6455 version > load csgo-practicemode  via disabled folder & load manually via rcon OR instantly crash with csgo-practicemode on "plugins" folder.

**Comment by Erfa** [comment]
My server is also crashing after the latest CS:GO update, not sure if it's related to practice mode. Here is my log:
```
Client "Erfa" connected (192.168.0.10:27005).
RecordSteamInterfaceCreation (PID 20192): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 20192): SteamUtils008 / Utils
RecordSteamInterfaceCreation (PID 20192): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 20192): SteamGameServerStats001 / GameServerStats
RecordSteamInterfaceCreation (PID 20192): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 20192): STEAMINVENTORY_INTERFACE_V001 / Inventory
RecordSteamInterfaceCreation (PID 20192): STEAMUGC_INTERFACE_VERSION008 / UGC
RecordSteamInterfaceCreation (PID 20192): STEAMAPPS_INTERFACE_VERSION008 / Apps
L 11/19/2019 - 22:49:20: World triggered "Round_Start"
L 11/19/2019 - 22:49:20: server_cvar: "sm_nextmap" "de_dust"
L 11/19/2019 - 22:49:21: "Erfa<2><STEAM_1:0:*******><>" STEAM USERID validated
PutClientInServer: no info_player_start on level
L 11/19/2019 - 22:49:22: "Erfa<2><STEAM_1:0*******><>" entered the game
Segmentation fault (core dumped)
BFD: warning: /home/csgoserver/serverfiles/core is truncated: expected core file size >= 338690048, found: 1019904
Cannot access memory at address 0xf7f61924
Cannot access memory at address 0xf7f61920
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf7f61924
Cannot access memory at address 0xf7f61920
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
```

**Comment by zonic5** [comment]
Me 2, and i think it's because of the practice mod (the server works when i uninstall practice mod)
Got this when trying 2 connect:

connect pro01.swifthosting.dk:XXXXX;pasword XXXXXXXXX
**** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#Panorama_CSGO_Spray_Cursor_Hint' on panel 'RosettaInfoText'
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
**** Panel  has fill-parent-flow for height, but isn't in a flowing down or up layout
PNG load error Interlace handling should be turned on when using png_read_image
Connecting to public(85.10.209.70:29031) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
#Valve_Reject_Connect_From_Lobby
**** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'PopupManager'
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_MAINMENU
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_MAINMENU
PNG load error Interlace handling should be turned on when using png_read_image
] connect pro01.swifthosting.dk:29031; password Schouwisawesome
**** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#Panorama_CSGO_Spray_Cursor_Hint' on panel 'RosettaInfoText'
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
**** Panel  has fill-parent-flow for height, but isn't in a flowing down or up layout
Connecting to public(85.10.209.70:29031) ...
Server using 'friends' lobbies, requiring pw yes, lobby id ffffffffffffffff
Connected to 85.10.209.70:29031

Counter-Strike: Global Offensive
Map: de_dust2
Players: 1 (0 bots) / 12 humans
Build: 7621
Server Number: 2

SignalXWriteOpportunity(3)
No pure server whitelist. sv_pure = 0
Error reading file resource/overviews/de_dust2_radar_spectate.dds.
ZoNiC connected.
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_INGAME
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--TERRORIST"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--CT"! Panel is possibly created dynamically.

Server connection timed out.
**** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'PopupManager'
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_MAINMENU
DispatchAsyncEvent backlog, failed to dispatch all this frame. 877 of 2410 remaining

**Comment by MikkelDK** [comment]
We can only wait....until @splewis will fix! ;)

**Comment by cybersteel8** [comment]
Yeah, I moved csutils.smx and practicemode.smx into the disabled folder to get the server to work :(

**Comment by splewis** [comment]
My server works fine on `SourceMod 1.10.0.6455, by AlliedModders LLC` (linux) with practicemode. 

I'd suggest anyone with crashes simply update SM, and make sure they have up to date gamedata files (you can do that by simply restarting your server - unless you disabled SM's auto updater functionality).

**Comment by MikkelDK** [comment]
Works fine here now =D 

//Closed.

**Comment by Erfa** [comment]
I updated my SourceMod version, now it works again. Thanks for the tip!

**Comment by zonic5** [comment]
Works for me 2, thx a lot!
