### ISSUE TITLE
.countdown not working.

### ISSUE THREAD

**Issue by rodrigo-apoc** [splewis/csgo-practice-mode#156]
# Expected behavior
Starts a countdown timer for the duration specified (in seconds).

### Actual behavior
Nothing happens.

### Steps to reproduce
- Plugin version: 1.3.3
- Sourcemod version: 1.10
- Steps to reproduce (please be specific): Just using the command on Mirage map.

**Comment by splewis** [comment]
The command is new - it's not in version 1.3.3 yet. It'll be in the next version. That's why it's not on the readme for 1.3.3: https://github.com/splewis/csgo-practice-mode/blob/1.3.3/README.md. 

I realize it's a bit confusing though, since the current README is what shows up on the main page - in the meantime you could use a development build (as described here: https://github.com/splewis/csgo-practice-mode#download) to get the command.

**Comment by rodrigo-apoc** [comment]
I see now. Thanks for the reply and congrats for this tool, it's really helpful for csgo teams.

I know it's not the right place/thread for this, but what we (users) can expect about source 2? 
Do you plan to upgrade or make a new version of PracticeMode when csgo changes to S2?

**Comment by splewis** [comment]
>  but what we (users) can expect about source 2?

I have no idea. I don't know anything about it.
