### ISSUE TITLE
Can't change dry run freezetime 

### ISSUE THREAD

**Issue by Zolo-amgaa** [splewis/csgo-practice-mode#188]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Changed value of 
g_DryRunFreezeTimeCvar = CreateConVar("sm_practicemode_dry_run_freeze_time", "6",
                                        "Freezetime after running the .dryrun command.");
to 
g_DryRunFreezeTimeCvar = CreateConVar("sm_practicemode_dry_run_freeze_time", "11",
                                        "Freezetime after running the .dryrun command.");
so that: 
.dryrun with freezetime of 11 seconds 

### Actual behavior
.dryrun won't change from 6 seconds 

### Steps to reproduce
- Plugin version: 2.9.5
- Sourcemod version:

**Comment by splewis** [comment]
> Changed value of
g_DryRunFreezeTimeCvar = CreateConVar("sm_practicemode_dry_run_freeze_time", "6",
"Freezetime after running the .dryrun command.");
to
g_DryRunFreezeTimeCvar = CreateConVar("sm_practicemode_dry_run_freeze_time", "11",
"Freezetime after running the .dryrun command.");
so that:
.dryrun with freezetime of 11 seconds

What specifically do you mean by this? Did you edit the source code? You should change values in `cfg/sourcemod/practicemode.cfg`  as https://github.com/splewis/csgo-practice-mode#convars mentions.

**Comment by Zolo-amgaa** [comment]
I am so sorry to waste your time. Thank you very much for this GOAT plugin

**Comment by Zolo-amgaa** [comment]
Out of pure curiosity, why didn't me changing that line of source code work?

**Comment by splewis** [comment]
The source code (.sp files) have to be compiled into a binary file that sourcemod uses (.smx files).

Also - that line of code sets the *default* value of the cvar only - the values in the .cfg file will overwrite it anyway, so unless it's a fresh install (so the .cfg file won't exist yet) changing the cvar default value wouldn't have the intended effect anyway.
