### ISSUE TITLE
How to invite my friends to practic on practic server

### ISSUE THREAD

**Issue by KatarinaGrujic** [splewis/csgo-practice-mode#196]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by PlamAtom** [comment]
If it is your private home server, you need to set up "port forwarding", otherwise send the IP address specified by the host provider.  
https://www.youtube.com/results?search_query=csgo+port+forwarding

I guess you have a token, if not here:
https://steamcommunity.com/dev/managegameservers

Not working and urgend? Try Hamachi 
https://vpn.net/
