### ISSUE TITLE
Disabling solid teammates does not work

### ISSUE THREAD

**Issue by KeT0M** [splewis/csgo-practice-mode#21]
### Expected behavior
Disabling solid teammates should change mp_solid_teammates 1 to mp_solid_teammates 0.

### Actual behavior
mp_solid_teammates stays at 1 regardless of whether I choose to disable it or not.

### Steps to reproduce
- Plugin version: CS:GO PracticeMode (1.1.2)
- Sourcemod version: SourceMod 1.8.0.5973

**Comment by splewis** [comment]
You're right - thanks for the bug report.

The reason this doesn't work is that practicemode works through a config that defines "enabled" cvars - cvars set when it the option is turned on:
```		"solidteammates"
		{
			"name"		"Solid teammates"
			"default"		"enabled"
			"enabled"
			{
				"mp_solid_teammates"		"1"
			}

		}
```

It doesn't explicitly say what happens when it is disabled, so it just remembers what the cvar was **before** the option got turned on. For almost every server, mp_solid_teammates is already 1. So practicemode thinks the "disabled" setting should still set mp_solid_teammates to 0.

I might rethink how the config works, maybe explicitly setting "disabled" cvars so this work more reliably.

**Comment by splewis** [comment]
This should be fixed now. You could get a development build from https://ci.splewis.net/job/csgo-practice-mode/lastStableBuild/ if you'd like.

The change would at least require a config change to addons/sourcemod/configs/practicemode.cfg to the "solidteammates" section to look like:
```

		"solidteammates"
		{
			"name"		"Solid teammates"
			"default"		"enabled"
			"enabled"
			{
				"mp_solid_teammates"		"1"
			}
			"disabled"
			{
				"mp_solid_teammates"		"0"
			}
		}
```
