### ISSUE TITLE
.delete .timer .cats  feature request

### ISSUE THREAD

**Issue by deepthought-s** [splewis/csgo-practice-mode#7]
First of all, let me tell you how awesome your plugin is. I setup a server for my friends to do some strats together and it really helps to learn nades and flashes... Good Job!
So my questions: 
- Is there a way to reset ids for nades when you deleted the last one?
- Can you add nades to a category later on? Not only the last nade id!?
- It would be so awesome if you could automate .timer so it starts when you start walking/mouse1 and ends on mouse1/stop walking.
- I assume .worstspawn looks for the spawn thats the farest away from the spot you are standing. Does it calculate it by "air-distance"?
- can you add a timer for molotovs and smokes, how long they take from throwing to poping? Very usefull to time your smokes perfectly.
- can you update the .help and wikipage for easier useage? I went through the sourcecode to find the commands .cats .cat .timer .worstspawn and how they work.

Thanks again for the awesome plugin.

**Comment by deepthought-s** [comment]
Ok I went through your sourcecode and found some answers. If you would update your commandlist on the wikipage and .help you could make it a lot easier for some ppl :).
I would love to see and update for the timer command, that would make it rly awesome.
BTW is there a way to reset the color setup for players. Each time someone joins the wrong team first and then changes teams we and up with the same radarcolor -> same nadetrail color.

**Comment by splewis** [comment]
Some good suggestions there. I'll try the automating .timer and seeing if I can display the duration for smokes/molotovs to land.

The grenade ids are intended to never be changed (think if it were a SQL database, the primary key would be steamid + id), so no. 

If you .cat or .addcat it will use the last grenade you saved (.save) or went to (.goto or via .nades menu). 

I know the descriptions are lacking. Many of these commands are new and somewhat experimental. Part of the problem is printing tons of things to in-game chat is hard to read. I might try doing a wiki page then .help will open up that page in a motd-window.

**Comment by deepthought-s** [comment]
Perfect! Thank you a thousand times, top-notch-developer. In my opinion a print to the console or textchat is fine aswell since you can scroll both, but with motd it would be even better.

**Comment by splewis** [comment]
These should all be implemented now.
